14172 - Update "How does it work?"
bcgov/sbc-auth pull request #2183
Opened 2022-12-12 21:14 UTC by ketaki-deodhar

*Issue #:*
https://github.com/bcgov/entity/issues/<14172>

*Description of changes:*
Update "How does it work?" text

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

2022-12-12 22:07 UTC, kialj876 commented
Do these changes need to wrapped in a feature flag? I don't think we would want to release this until the different company types are available in the business app.

It would probably be beneficial to have the text come from the feature flag unless all the new types are getting launched at the same time

2022-12-12 22:36 UTC, ketaki-deodhar commented
> Do these changes need to be wrapped in a feature flag? I don't think we would want to release this until the different company types are available in the business app.
> 
> You might need different variations of this if the types aren't being released at the same time

Yes. You are right. Missed it. Will fix it.

2022-12-14 17:15 UTC, ketaki-deodhar commented
> Do these changes need to be wrapped in a feature flag? I don't think we would want to release this until the different company types are available in the business app.
> 
> You might need different variations of this if the types aren't being released at the same time

Added feature flag and fixed tests.

2022-12-14 22:16 UTC, seeker25 approved these changes

2022-12-14 22:16 UTC, severinbeauvais commented
Please update app version. Re: https://github.com/bcgov/sbc-auth/blob/main/auth-web/package.json

2022-12-14 22:17 UTC, seeker25 commented
Also: Are these flags setup in DEV/TEST/PROD?

2022-12-14 22:19 UTC, severinbeauvais commented
> Also: Are these flags setup in DEV/TEST/PROD?

Yes, this is an existing flag in LD sbc-auth project.
Dev: true
Test: true
Production: false

2022-12-14 22:22 UTC, severinbeauvais approved these changes
LGTM.

Please create a new Tech Debt ticket to remove this flag and conditional code once this feature is deployed to Prod.

2022-12-14 22:32 UTC, merged

2022-12-14 22:35 UTC, kialj876 requested changes
Hey Ketaki,

You're PR introduces a lot of duplicate code that can be avoided by using computed values for your text instead of v-if/else blocks, can you please update it based on my comments?
It will make it easier in the future to read / refactor / do styling updates etc.

Other than that I think it is looking good 👍

2022-12-14 22:35 UTC, kialj876 commented on auth-web/src/views/auth/home/IncorpOrRegisterView.vue
> +              <div v-if="enableBcCccUlc">
can you please add a computed value for `bulletPoints` that changes based on the `enableBcCccUlc` flag instead of having the v-if/else clause?

2022-12-14 22:35 UTC, kialj876 commented on auth-web/src/views/auth/home/IncorpOrRegisterView.vue
> +            <div v-if="enableBcCccUlc">
same thing here for `expansionPanels`

2022-12-14 22:35 UTC, kialj876 commented on auth-web/src/views/auth/home/MaintainBusinessView.vue
> +          <div v-if="enableBcCccUlc">
same idea here

2022-12-14 22:35 UTC, kialj876 commented on auth-web/src/components/auth/common/NumberedCompanyTooltip.vue
> +      <span v-on="on" class="tooltip-text" v-if="enableBcCccUlc">Numbered Company</span>
pls rmv v-if/else and do a computed value for the text here

2022-12-14 22:35 UTC, kialj876 commented on auth-web/src/components/auth/common/NumberedCompanyTooltip.vue
> +      <div v-if="enableBcCccUlc">
same thing in here