#16721, #16227, #15770: Initial changes to my-business registry dashb…
bcgov/sbc-auth pull request #2376
Opened 2023-07-04 17:47 UTC by marzmehr

…oard

*Issue #:*
https://github.com/bcgov/entity/issues/16721
https://github.com/bcgov/entity/issues/16227
https://github.com/bcgov/entity/issues/15770

*Description of changes:*
Initial UI changes
Note: API integration has been completed for business search.

These changes should not be merged into main until all tickets under [#16518](https://github.com/bcgov/entity/issues/16518) have been completed and merged here.

Note: This PR was originally reviewed under https://github.com/bcgov/sbc-auth/pull/2375 . But the feature branch name 'release-3.0.0' is not suitable for this code change.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

2023-07-04 17:54 UTC, marzmehr commented
I will delete the invalid feature branch release-3.0.0. The comments on the PR so far are as follows:
![Screenshot from 2023-07-04 10-51-42](https://github.com/bcgov/sbc-auth/assets/60238408/7e343407-8a03-433c-8535-4cdf610e33da)
![Screenshot from 2023-07-04 10-51-29](https://github.com/bcgov/sbc-auth/assets/60238408/7ba70b38-59c2-4d04-be37-581afdf8104c)
![Screenshot from 2023-07-04 10-51-14](https://github.com/bcgov/sbc-auth/assets/60238408/7752c8ab-600f-4f7f-895b-889a419a41e5)
![Screenshot from 2023-07-04 10-51-02](https://github.com/bcgov/sbc-auth/assets/60238408/af917249-2ffd-46aa-9a9d-385d201cfed9)

@severinbeauvais , @seeker25 please add any additional comments here.

2023-07-04 17:57 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/SearchBusinessNameRequest.vue
> +  // private readonly addBusiness!: (loginPayload: LoginPayload) => any
Remove commented

2023-07-04 18:00 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/SearchBusinessNameRequest.vue
> +  // $refs: {
Remove commented

2023-07-04 18:32 UTC, severinbeauvais commented
> Note: This PR was originally reviewed under #2375 . But the feature branch name 'release-3.0.0' is not suitable for this code change.

So the idea is that we'll pick an app version just before merging this feature branch to main?

2023-07-04 20:03 UTC, severinbeauvais commented on auth-web/src/components/auth/manage-business/EntityManagement.vue
> +  }
This should not be needed because it should not be possible to add a business that is already added.

2023-07-04 20:06 UTC, severinbeauvais commented on auth-web/src/components/auth/manage-business/SearchBusinessNameRequest.vue
> +  manageBusinessDialog = { show: false }
Normally this is a boolean not an object. Are you doing it this way for a particular reason?

2023-07-04 20:07 UTC, severinbeauvais commented on auth-web/src/components/auth/manage-business/ManageBusinessDialog.vue
> +      v-model="dialog.show"
`dialog` is normally a boolean (as per above comment).

2023-07-04 20:09 UTC, severinbeauvais commented on auth-web/src/components/auth/manage-business/ManageBusinessDialog.vue
> +    return 'Enter the password you have setup in Coporate Online, must be 8 to 15 characters'
Typo on lines 262 and 263.

setup -> set up
Coporate -> Corporate

2023-07-04 20:11 UTC, severinbeauvais commented on auth-web/src/components/auth/manage-business/NameRequestLookup.vue
> +  SEARCHING = 'searching',
Does this need a TYPING state also? And the other changes you made to BusinessLookup?

2023-07-04 20:15 UTC, severinbeauvais requested changes
There are still outstanding comments from the previous PR.

Also for next time: don't do more than your ticket requires. For example, you have partly implemented the NR lookup -- I think it would be better to implement nothing or all -- unless you intend to implement tickets 16720 and 16722? (Entities Team will thank you but this has to be decided between your PO and ours.)

2023-07-05 16:57 UTC, severinbeauvais commented
/gcbrun

2023-07-05 18:08 UTC, pwei1018 commented
/gcbrun

2023-07-11 15:24 UTC, severinbeauvais commented
/gcbrun

2023-07-12 15:14 UTC, severinbeauvais commented on auth-web/src/resources/MhrSubProducts.ts
> +export const MhrSubProducts: any = [
Could you use SubProductConfigIF here instead of `any`?

2023-07-12 15:15 UTC, severinbeauvais commented on auth-web/src/models/SubProductConfigIF.ts
> +    type: string
Should be type `AssetsRoles`?

2023-07-12 15:17 UTC, severinbeauvais commented on auth-web/tests/unit/components/SubProductSelector.spec.ts
> +// @ts-ignore
Why do you need this? I think we should not be disabling tools in the unit tests.

2023-07-14 15:30 UTC, severinbeauvais commented on auth-web/src/components/auth/manage-business/AccountAuthorizationRequest.vue
> +  <div class="pa-5">
I recommend adding an id to all components (or classname if there can be multiple instances of the component). Otherwise, looks good!

2023-07-28 16:36 UTC, Jxio commented on auth-web/src/components/auth/manage-business/NameRequestLookup.vue
@rodrigo-barraza we might don't need this, based on ux, the NameRequestLookup and BusinessLookup pretty much same, could just use one lookup.

2023-07-28 16:37 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/NameRequestLookup.vue
Good idea Jia

2023-07-31 23:37 UTC, seeker25 commented
Closing, Rodrigo is splitting this into separate PR's

2023-07-31 23:37 UTC, closed without merging