15769 - Manage a B.C. Business modal view for Corporation
bcgov/sbc-auth pull request #2468
Opened 2023-08-18 18:01 UTC by rodrigo-barraza

*Issue #:15769*
https://github.com/bcgov/entity/issues/15769

Additions and changes for managing a B.C. business modal for corporations. Visual fixes to related modals, and copy updates.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

2023-08-18 18:04 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/ManageBusinessDialog.vue
> +                  v-if="isBusinessLegalTypeCorporation || isBusinessLegalTypeCoOp"
if you run npm run lint, it should reorder these for you

2023-08-18 18:05 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/ManageBusinessDialog.vue
> +                      Confirm authorization using your {{isBusinessLegalTypeCorporation || isBusinessLegalTypeCoOp ? 'registered office' : isBusinessLegalTypeSPorGP ? 'business' : ''}} email address
Could we move this to a computed? it's fairly crowded

2023-08-18 18:05 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/ManageBusinessDialog.vue
> +                      An email will be sent to the {{ isBusinessLegalTypeCorporation || isBusinessLegalTypeCoOp ? 'registered office' : isBusinessLegalTypeSPorGP ? 'business' : ''}} contact email of
Move to computed please

2023-08-18 18:05 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/ManageBusinessDialog.vue
> +      } else if (isBusinessLegalTypeSPorGP.value) {
isBusinessLegalTypeSPorGP == isFirm I think

2023-08-18 18:07 UTC, seeker25 commented on auth-web/src/components/auth/common/HelpDialog.vue
> +        padding: 16px 40px 0 40px;
Good, this is for all of the custom fitting for the dialogs. Should we use this for all dialogs perhaps?

2023-08-18 18:08 UTC, seeker25 reviewed
Please nudge package.json and package lock as well -  I will be moving it up a minor version when we merge to main though

2023-08-18 18:14 UTC, Jxio commented
/gcbrun

2023-08-18 20:21 UTC, seeker25 commented
/gcbrun

2023-08-18 20:27 UTC, pwei1018 commented
Temporary Url for review: https://bcregistry-account-dev--pr-2468-ozcq53tu.web.app

2023-08-18 21:07 UTC, Jxio commented
![image](https://github.com/bcgov/sbc-auth/assets/16507223/2bb9322e-9aa3-43fc-96ac-d2eaae5d5c2d)
email not included in the dialog, might need confirm with UX

2023-08-18 21:14 UTC, Jxio commented
<img width="1449" alt="image" src="https://github.com/bcgov/sbc-auth/assets/16507223/a8268bb5-4725-4a29-b0ab-f4bfa02886b1">
did you implemented -^ ?

2023-08-18 21:20 UTC, Jxio commented
![image](https://github.com/bcgov/sbc-auth/assets/16507223/701aa708-0209-4171-921d-043d98352e3e)
BE is ready, can talk to Ody and get it filled

2023-08-18 21:22 UTC, Jxio commented
![image](https://github.com/bcgov/sbc-auth/assets/16507223/0dd38b37-39db-47cc-b2bc-29b6ff9f59da)
I don't see re-send email function.

2023-08-19 22:23 UTC, seeker25 commented
If there is no masked email returned, there's another ticket that's supposed to handle it and notify the user

2023-08-19 22:23 UTC, seeker25 commented
https://github.com/bcgov/entity/issues/17057

2023-08-21 15:49 UTC, Jxio commented
/gcbrun

2023-08-21 15:55 UTC, pwei1018 commented
Temporary Url for review: https://bcregistry-account-dev--pr-2468-ozcq53tu.web.app

2023-08-22 15:32 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
> +      if (isCurrentOrganization(affiliationInviteInfos[0]?.toOrg?.id)) {
Might be a better idea to rethink using so many chaining conditionals

2023-08-22 15:32 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
> +      if (item?.affiliationInvites?.[0]?.status === 'PENDING') {
ENUM

2023-08-22 15:34 UTC, seeker25 commented on auth-web/src/store/modules/business.ts
> +        const isToOrgAndPending = affiliationInviteInfo?.toOrg?.id === this.currentOrganization.id &&
This code needs to be refactored for code complexity, managed to do that in my latest PR

2023-08-22 15:35 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/ManageBusinessDialog.vue
> +          (!isBusinessLegalTypeFirm.value || isCertified.value) &&
You're already handling LegalTypeFirm above, this can be cleaned up

2023-08-22 15:38 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
> +      if (item?.affiliationInvites?.[0]?.status === 'PENDING') {
enum

2023-08-22 15:44 UTC, seeker25 requested changes
There are some concerns to address before this gets merged

2023-08-23 23:59 UTC, seeker25 approved these changes

2023-08-23 23:59 UTC, seeker25 commented
/gcbrun

2023-08-24 00:00 UTC, merged

2023-08-24 00:05 UTC, pwei1018 commented
Temporary Url for review: https://bcregistry-account-dev--pr-2468-ozcq53tu.web.app