17636 - Refactoring of AuthorizationRequestSentDialog, further unit testing
bcgov/sbc-auth pull request #2536
Opened 2023-09-13 16:22 UTC by rodrigo-barraza

*Issue #:*
https://github.com/bcgov/entity/issues/17636

*Description of changes:17636*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

2023-09-13 17:49 UTC, seeker25 commented
From the other ticket: 

![Uploading image.png…]()

2023-09-14 15:53 UTC, Jxio commented
/gcbrun

2023-09-14 16:03 UTC, seeker25 commented
Still missing the changes in the screenshots?

2023-09-14 16:04 UTC, seeker25 requested changes
Missing Ethan's UX changes

2023-09-15 15:47 UTC, seeker25 commented
![image](https://github.com/bcgov/sbc-auth/assets/3484109/f7277653-eb36-463a-84b7-0a7f8bdbd501)

2023-09-15 15:48 UTC, seeker25 commented
Ticket number not in the title

2023-09-15 15:53 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2536-zrt9q6wv.web.app

2023-09-15 15:57 UTC, seeker25 commented
Looks good
![image](https://github.com/bcgov/sbc-auth/assets/3484109/68ae7a62-c23d-4341-80de-e392051e2f90)

2023-09-15 15:59 UTC, seeker25 commented on auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
> +              style="margin-top: 2px;"
Duplicated by styling

2023-09-15 16:00 UTC, Jxio approved these changes

2023-09-15 16:45 UTC, merged