17596 - Add support for affiliations in multiple environments
bcgov/sbc-auth pull request #2559
Opened 2023-09-19 16:12 UTC by kris-daxiom

*Issue #:*
https://github.com/bcgov/entity/issues/17596

*Description of changes:*
Added environment in the affiliations model and changed the org and modified affiliation endpoints, services to pass the environment to the model.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

2023-09-19 16:43 UTC, seeker25 commented on auth-api/src/auth_api/resources/v1/org.py
> +                org_id, env, business_identifier, request_json.get('email'),
Too many parms, use a dataclass or dict

2023-09-19 16:47 UTC, seeker25 commented on auth-api/src/auth_api/resources/v1/org.py
>              response, status = AffiliationService.create_affiliation(
Too many parms, use a dataclass or dict

2023-09-19 18:44 UTC, ochiu commented on auth-api/src/auth_api/resources/v1/affiliation_invitation.py
> +def _get_environment():
I see this duplicated, perhaps move into utils?

2023-09-19 20:34 UTC, ochiu commented on auth-api/src/auth_api/services/affiliation.py
> +        affiliation.environment = environment
Is this needed since it is already being passed in when instantiating the model?

2023-09-19 21:13 UTC, ochiu commented on auth-api/tests/unit/services/test_affiliation_invitation.py
> +                                                                                            User(user), '', 'test')
We should probably add additional tests that is more focused on testing the multi-environment nature of this change.

The existing updates are good for testing everything is working as previously, but probably not for the scenario it was implemented for, unless I am missing something?

2023-09-20 19:23 UTC, seeker25 commented on auth-api/src/auth_api/services/affiliation.py
> +    def delete_affiliation(org_id, business_identifier, environment: str = None, email_addresses: str = None,   # pylint: disable=too-many-arguments  # noqa: E501
too many arguments

2023-09-20 19:23 UTC, seeker25 commented on auth-api/src/auth_api/services/affiliation.py
> +    def create_new_business_affiliation(affiliation_data: AffiliationData,  # pylint: disable=too-many-locals, too-many-branches, too-many-statements  # noqa: E501
too many branches, means we should refactor into functions

2023-09-20 19:24 UTC, seeker25 reviewed
see above

2023-09-20 23:42 UTC, seeker25 commented on auth-api/src/auth_api/services/affiliation.py
> +    def create_new_business_affiliation(affiliation_data: AffiliationData,  # pylint: disable=too-many-locals, too-many-branches, too-many-statements  # noqa: E501
It was added in this PR, there was no too many branches code smell or linting issue before - I'm fairly positive

2023-09-21 19:23 UTC, seeker25 commented on auth-api/tests/unit/services/test_affiliation.py
> +    env = 'test'
Suggestion: enum for environments?

2023-09-21 19:24 UTC, seeker25 commented on auth-api/src/auth_api/services/affiliation.py
> +    def delete_affiliation(delete_affiliation_request: DeleteAffiliationRequest, environment: str = None):
suggestion: `delete_affiliation_request` -> `request`, that way you don't have to remap like on 310

2023-09-21 19:24 UTC, seeker25 commented on auth-api/migrations/versions/2023_09_05_1ddf3b37e17f_.py
> +    op.add_column('affiliations', sa.Column('environment', sa.String(length=20), nullable=False))
Wont this have issues where environment is already empty?

2023-09-21 19:25 UTC, seeker25 commented on auth-api/src/auth_api/models/affiliation.py
> +    def find_affiliations_by_business_identifier(cls, business_identifier: str, environment: str):
Suggestion, it might be easier to just use 

`environment = get_request_environment()` everywhere instead of passing it down

2023-09-21 19:30 UTC, seeker25 reviewed
see above

2023-09-22 03:19 UTC, seeker25 commented on auth-api/src/auth_api/models/affiliation.py
> +    def find_affiliations_by_business_identifier(cls, business_identifier: str, environment: str):
Don't use the request object?  Figure out another way to determine if it's sandbox?

2023-09-22 03:20 UTC, seeker25 commented on auth-api/migrations/versions/2023_09_05_1ddf3b37e17f_.py
> +    op.add_column('affiliations', sa.Column('environment', sa.String(length=20), nullable=False))
Ok, so merging this PR, it's going to explode and fail wont it? nullable should be set to True until you run the update script?

2023-09-22 03:20 UTC, seeker25 commented on auth-api/src/auth_api/resources/v1/org.py
> +            affiliation_data = AffiliationData(org_id=org_id, business_identifier=business_identifier,
Too many params

2023-09-22 03:22 UTC, seeker25 requested changes
I think there's a better way of doing this than lugging environment through all of the parameters. Why not just stand up a sandbox instance of auth-api? Similar to pay? ( I think this is a bit longer term goal Thor was talking about )

Another alternative, make some sort of model level code that automatically sets / queries the environment. 

If we look at the base model we already have something that uses request:

```
    @classmethod
    def create_activity(cls, obj, is_delete=False):
        """Create activity records if the model is versioned."""
        if isinstance(obj, VersionedModel) and not current_app.config.get('DISABLE_ACTIVITY_LOGS'):
            if is_delete:
                verb = 'delete'
            else:
                verb = 'update' if obj.modified_by is not None else 'create'

            activity = activity_plugin.activity_cls(verb=verb, object=obj, data={
                'user_name': g.jwt_oidc_token_info.get('preferred_username',
                                                       None) if g and 'jwt_oidc_token_info' in g else None,
                'remote_addr': fetch_remote_addr()
            })

            db.session.add(activity)
```
This already uses request -^  (`fetch_remote_addr()`)

```


def fetch_remote_addr():
    # Return None if we are outside of request context.
    if _app_ctx_stack.top is None or _request_ctx_stack.top is None:
        return
    return request.remote_addr
```

We could add in one of these to check for the entity you want to add environment for - if it's the right entity it can look at g context and grab the environment from there. 

EG.  For inserting or update the environment:

```
@event.listens_for(Org, 'before_insert')
def receive_before_insert(mapper, connection, target):  # pylint: disable=unused-argument; SQLAlchemy callback signature
    """Rejects invalid type_codes on insert."""
    org = target
    if org.type_code in (OrgTypeEnum.SBC_STAFF.value, OrgTypeEnum.STAFF.value):
        raise BusinessException(
            Error.INVALID_INPUT,
            None
        )


@event.listens_for(Org, 'before_update', raw=True)
def receive_before_update(mapper, connection, state):  # pylint: disable=unused-argument; SQLAlchemy callback signature
    """Rejects invalid type_codes on update."""
    if Org.type_code.key in state.unmodified:
        return
    raise BusinessException(
        Error.INVALID_INPUT,
        None
    )

```
You could easily set the environment here -^ for the entities you need. If its short and doesn't touch the resources / services / models - it's very easy to rip it out again and fix it later. 


For querying:

I think even just a helper method would suffice:

EG.
    @classmethod
    def query_active_users(cls):
        return cls.query.filter_by(is_deleted=False)

Probably could override the BaseQuery - check if it's the entity you need, if it is, filter out for environment - so it's done in one spot. 


EG.

````
    self.Affiliation.query_class = query_class

class Affiliation(db.Model):
    query_class = EnvironmentQuery

class EnvironmentQuery(Query):
    def all_include_environment(self):
          return self.filter(Affiliation.environment == <env>).all()
    def first_include_environment(self):
          return self.filter(Affiliation.environment == <env>).first()
````
etc


Looking at flask sqlalchemy locally:

![image](https://github.com/bcgov/sbc-auth/assets/3484109/1df2e909-5c90-4719-8692-9efe3db2a681)

It's using request for pagination.

2023-09-22 16:26 UTC, seeker25 commented
I'm not comfortable with lugging around the environment variable from the resource down to the model. @ochiu agrees with me as well.

2023-09-22 17:00 UTC, seeker25 commented
Sometimes it takes time for thoughts to percolate. @thorwolpert @kialj876 What are your thoughts on this PR?

2023-09-29 19:33 UTC, seeker25 commented
@kris-daxiom could we set nullable = True in the migration, plus fix the merge conflict - then merge?

2023-09-29 19:33 UTC, seeker25 approved these changes

2023-10-03 20:47 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2559-x9lrl7vq.web.app

2023-10-03 23:12 UTC, merged