17869_part1 - AUTH-WEB CFS Account Number Added
bcgov/sbc-auth pull request #2601
Opened 2023-10-13 22:19 UTC by AbrahamRostampoor

*Issue #:17869
https://github.com/bcgov/entity/issues/17869

*Description of changes:*
The CFS Account # is added to step 4 of "Make a Payment" page.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

2023-10-13 22:21 UTC, AbrahamRostampoor commented
/gcbrun

2023-10-13 22:27 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2601-2qugxl7x.web.app

2023-10-13 22:33 UTC, AbrahamRostampoor commented
/gcbrun

2023-10-13 22:39 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2601-2qugxl7x.web.app

2023-10-16 20:30 UTC, seeker25 commented on package-lock.json
> +  "name": "sbc-auth",
Please remove this file and update package.json, then update package-lock.json by using `npm i`

2023-10-17 17:11 UTC, seeker25 requested changes
wrong package-lock.json added, package.json needs to be updated and package-lock.json needs to be updated

2023-10-17 19:28 UTC, closed without merging