17869 - AUTH_WEB Added CFS Account Number
bcgov/sbc-auth pull request #2608
Opened 2023-10-17 20:42 UTC by AbrahamRostampoor

*Issue #:*
https://github.com/bcgov/entity/issues/17869

*Description of changes:*
Created a new branch. Added CFS account number to auth-web payment page.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

2023-10-17 20:42 UTC, AbrahamRostampoor commented
/gcbrun

2023-10-17 20:48 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2608-6osobl5x.web.app

2023-10-17 22:41 UTC, Jxio commented on auth-web/src/components/pay/PayWithOnlineBanking.vue
> +        <li>Enter BC Registries and Online Services account number: {{ cfsAccountId }}</li>
I think color for cfsaccount # is #495057 at design doc

2023-10-17 22:43 UTC, Jxio commented on auth-web/src/components/pay/PayWithOnlineBanking.vue
>          <li>Enter "BC Registries and Online Services" as payee</li>
"BC Registries and Online Services" color seems need to update, check with Ethan.

2023-10-17 22:43 UTC, Jxio commented
update package version

2023-10-18 15:40 UTC, seeker25 requested changes
![image](https://github.com/bcgov/sbc-auth/assets/3484109/09a79c0b-bf17-48bd-8b85-643e7ac4cd32)

2023-10-18 15:41 UTC, seeker25 commented
package + package-lock update please

2023-10-18 17:35 UTC, AbrahamRostampoor commented
/gcbrun

2023-10-18 17:40 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2608-6osobl5x.web.app

2023-10-18 18:26 UTC, AbrahamRostampoor commented
/gcbrun

2023-10-18 18:27 UTC, ethantspitt commented
Is it possible to attach related screenshot? using the bcbrun link seems not showing the new changes:
<img width="817" alt="Screenshot 2023-10-18 at 11 20 15 AM" src="https://github.com/bcgov/sbc-auth/assets/116669121/4d32be9e-a934-4240-9677-4a2f1bcc6863">

2023-10-18 18:32 UTC, AbrahamRostampoor commented
> Is it possible to attach related screenshot? using the bcbrun link seems not showing the new changes: <img alt="Screenshot 2023-10-18 at 11 20 15 AM" width="817" src="https://user-images.githubusercontent.com/116669121/276361693-4d32be9e-a934-4240-9677-4a2f1bcc6863.png">

> Yes for sure Ethan. Here is the screenshot I got. please let me know if I should take another one.
<img width="1274" alt="MicrosoftTeams-image" src="https://github.com/bcgov/sbc-auth/assets/144154569/65ec4faa-58b1-4489-8cc4-333cc0f8bc94">

2023-10-18 18:32 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2608-6osobl5x.web.app

2023-10-18 18:58 UTC, AbrahamRostampoor commented
/gcbrun

2023-10-18 19:05 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2608-6osobl5x.web.app

2023-10-18 20:01 UTC, AbrahamRostampoor commented
/gcbrun

2023-10-18 20:06 UTC, Jxio approved these changes
LGTM!

2023-10-18 20:07 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2608-6osobl5x.web.app

2023-10-20 18:58 UTC, seeker25 approved these changes

2023-10-20 18:59 UTC, merged