19334 - Adding Get All Active EFT Organizations support
bcgov/sbc-auth pull request #2698
Opened 2024-01-31 15:23 UTC by rodrigo-barraza

*Issue #:19334*
https://github.com/bcgov/entity/issues/19334

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

2024-01-31 17:52 UTC, ochiu commented on auth-api/src/auth_api/services/org.py
> +            eft_payment_accounts = Org.get_eft_payment_accounts()
Looks like we are fetching all the eft accounts for every request. After the auth search we should have the ids we need to pass onto pay_api.

2024-01-31 18:00 UTC, seeker25 commented on auth-api/src/auth_api/services/org.py
> +        response = RestService.get(endpoint=f'{pay_api_url}/eft-accounts', token=token)
Alternatively, maybe we could put this in it's own route? not tied into org?

2024-02-01 22:27 UTC, seeker25 requested changes
EFT shouldn't be a concept in AUTH, it's a PAY concept

2024-02-01 22:32 UTC, ochiu commented
We can probably consider closing this PR once I complete the new simple org search route (I am implementing as part of this ticket).

We should be able to use the simple org search and the eft-shortnames search to get an existing list of LINKED accounts along with a list of the account ids to satisfy #19334 used for the linking modal ticket

2024-02-01 22:51 UTC, closed without merging