19414 - Account Management - add search for closed/historical accounts
bcgov/sbc-auth pull request #2850
Opened 2024-06-04 20:37 UTC by sameer0422

*Issue #:*
https://github.com/bcgov/entity/issues/19414

*Description of changes:* Account Management - add search for closed/historical accounts

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

2024-06-04 21:38 UTC, sameer0422 commented
/gcbrun

2024-06-04 21:42 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2850-k4dxwtt4.web.app

2024-06-04 22:01 UTC, seeker25 commented on auth-web/src/components/auth/common/AccountInActiveAlert.vue
> +@Component
Please rewrite using `composition-api`

2024-06-04 22:02 UTC, seeker25 commented on auth-web/src/components/auth/common/AccountInActiveAlert.vue
> +      ? this.formatDate(new Date(this.currentOrganization.modified)) : ''
Please use `moment` if possible `new Date(<string>)` has issues

2024-06-04 22:02 UTC, seeker25 commented on auth-web/src/components/auth/common/AccountInActiveAlert.vue
> +    display: flex;
there's a Vuetify class for this

2024-06-04 22:03 UTC, seeker25 commented on auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
> +        :to="pagesEnum.STAFF_DASHBOARD_InACTIVE"
Typo? InACTIVE?

should be INACTIVE?

2024-06-04 22:03 UTC, seeker25 commented on auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
> +        InActive
`Inactive`

2024-06-04 22:03 UTC, seeker25 commented on auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
> +    InActive = 'inactive-tab'
`Inactive`

2024-06-04 22:03 UTC, seeker25 commented on auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
> +    StaffInActiveAccountsTable,
`Inactive`

2024-06-04 22:03 UTC, seeker25 commented on auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
> +      code: TAB_CODE.InActive
`Inactive`

2024-06-04 22:04 UTC, seeker25 commented on auth-web/src/components/auth/staff/account-management/StaffInActiveAccountsTable.vue
> +export default class StaffInActiveAccountsTable extends Mixins(PaginationMixin) {
Please rewrite using `composition-api`

2024-06-04 22:04 UTC, seeker25 commented on auth-web/src/util/constants.ts
> +    STAFF_DASHBOARD_InACTIVE = '/staff/dashboard/inactive',
`InACTIVE` -> `INACTIVE`

2024-06-04 22:05 UTC, seeker25 commented on auth-web/src/views/auth/AccountSettings.vue
> +    <!-- InActive Account Banner-->
`Inactive`

2024-06-04 22:06 UTC, seeker25 commented on auth-web/src/components/auth/staff/account-management/StaffInActiveAccountsTable.vue
> +  protected getAccountTypeFromOrgAndAccessType (org:Organization): any {
Is this code duplicated somewhere? if it is.. probably best to refactor it?

2024-06-04 22:06 UTC, seeker25 requested changes
Looks good so far, but should be in composition-api

2024-06-04 22:33 UTC, seeker25 commented
use v-sanitize:

![image](https://github.com/bcgov/sbc-auth/assets/3484109/b7f1299c-e99f-4798-863f-2f26914b9529)

2024-06-04 22:33 UTC, seeker25 commented
Refactor, so there is less duplication:

![image](https://github.com/bcgov/sbc-auth/assets/3484109/856b4b0b-05db-4579-b729-1cec72b4bc38)

2024-06-05 02:12 UTC, seeker25 commented on auth-web/src/components/auth/staff/account-management/StaffInActiveAccountsTable.vue
> +  <div>
Unit test for this?

2024-06-11 18:21 UTC, sameer0422 commented on auth-web/src/components/auth/common/AccountInActiveAlert.vue
> +@Component
Fixed

2024-06-11 18:21 UTC, sameer0422 commented on auth-web/src/components/auth/common/AccountInActiveAlert.vue
> +      ? this.formatDate(new Date(this.currentOrganization.modified)) : ''
Fixed

2024-06-11 18:21 UTC, sameer0422 commented on auth-web/src/components/auth/common/AccountInActiveAlert.vue
> +    display: flex;
Fixed

2024-06-11 18:21 UTC, sameer0422 commented on auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
> +        :to="pagesEnum.STAFF_DASHBOARD_InACTIVE"
Fixed

2024-06-11 18:21 UTC, sameer0422 commented on auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
> +        InActive
Fixed

2024-06-11 18:21 UTC, sameer0422 commented on auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
> +    InActive = 'inactive-tab'
Fixed

2024-06-11 18:21 UTC, sameer0422 commented on auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
> +    StaffInActiveAccountsTable,
Fixed

2024-06-11 18:21 UTC, sameer0422 commented on auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
> +      code: TAB_CODE.InActive
Fixed

2024-06-11 18:22 UTC, sameer0422 commented on auth-web/src/util/constants.ts
> +    STAFF_DASHBOARD_InACTIVE = '/staff/dashboard/inactive',
Fixed

2024-06-11 18:22 UTC, sameer0422 commented on auth-web/src/views/auth/AccountSettings.vue
> +    <!-- InActive Account Banner-->
Fixed

2024-06-11 21:57 UTC, sameer0422 commented
/gcbrun

2024-06-11 22:01 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2850-k4dxwtt4.web.app

2024-06-12 01:27 UTC, seeker25 commented
Looks good, maybe 1 suggestion? the deactivated date? or updated_on show that in this screen?

![image](https://github.com/bcgov/sbc-auth/assets/3484109/d70d99d0-7f3a-41ca-8ea6-4af5e996fd7e)

2024-06-12 01:28 UTC, seeker25 commented on auth-web/src/views/auth/AccountSettings.vue
> +  // show baner for staff user and account inactive
a bit redundant?

2024-06-12 01:29 UTC, seeker25 approved these changes
Great job

2024-06-12 01:34 UTC, merged