20721 - Client changes from EFT to PAD
bcgov/sbc-auth pull request #2941
Opened 2024-08-01 17:58 UTC by Jxio

*Issue #:*
https://github.com/bcgov/entity/issues/20721
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

2024-08-01 22:37 UTC, Jxio commented on auth-web/src/components/auth/common/PaymentMethods.vue
> -        @click="paymentMethodSelected(payment)"
redundant, it always send two requests

2024-08-01 22:49 UTC, Jxio commented on auth-web/src/util/constants.ts
> +    MAKE_CC_PAYMENT = '/make-cc-payment/',
it's pay for outstanding balance by credit card, but says `MAKE_PAD_PAYMENT`

2024-08-01 22:54 UTC, Jxio commented
/gcbrun

2024-08-01 22:58 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2941-fp9gks8g.web.app

2024-08-01 23:19 UTC, Jxio commented
/gcbrun

2024-08-01 23:23 UTC, bcregistry-sre commented
Temporary Url for review: https://bcregistry-account-dev--pr-2941-fp9gks8g.web.app

2024-08-02 15:37 UTC, seeker25 commented
Why is paying for EFT via PAD an option? 

are you creating the CFS account for PAD.. waiting for the confirmation period to be over.. re-creating the invoices in PAD?
and reversing the invoices for EFT?

2024-08-02 15:38 UTC, seeker25 requested changes
Pay EFT balance with PAD, I don't think this works

2024-08-06 16:31 UTC, ochiu commented
Agreed, I believe we decided we will just go with the CC flow as we removed Option #2 from the ticket to pay with PAD.

2024-08-06 20:48 UTC, Jxio commented
I added feature flag of pay EFT balance by PAD.
Currently when user change from EFT to PAD, if it has remaining balances, it direct to pay outstanding balance screen, it only has cc option cause we don't have 'enable-eft-balance-by-pad' for now.

2024-08-06 22:26 UTC, Jxio commented
closing this ticket, will open another one for removing pad option

2024-08-06 22:26 UTC, closed without merging